trigger:
  branches:
    include:
      - main
      - dev

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'

  - script: npm ci
    displayName: Install Dependencies

  - script: npx playwright install --with-deps
    displayName: Install Playwright Browsers

  - script: npm run build
    displayName: Build App

  - script: npm run start &
    displayName: Start Web Server

  - script: npx playwright test --reporter=junit,html
    displayName: Run Playwright Tests

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results/**/*.xml'
      testRunTitle: 'Playwright Test Results'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'playwright-report'
      artifactName: 'Playwright HTML Report'
      publishLocation: 'Container'
    condition: succeededOrFailed()
